### ISSUE TITLE
Any idea how to test CXF with CDI (and local transport?) 

### ISSUE THREAD

**Issue by ieugen** [reta/jax-rs-2.0-cdi#2]
Hi @reta,

I'm developing a JAX-RS service with CXF and CDI and I your project helped. Thanks. 
Have you any ideas on how to test resources with CXF and CDI and local transport maybe?    

Regards,

**Comment by reta** [comment]
Hi!

Yeah, sure. The good starting point is Apache CXF systests themselves: please take a look on this project: https://github.com/apache/cxf/tree/master/systests/cdi/src/test/java/org/apache/cxf/systest/jaxrs. 

Basically, the procedure is pretty simple:
- run your app inside embedded Jetty / Tomcat
- run your tests

Let me know if you need any help or have more questions.
Thanks! 

Best Regards,
    Andriy Redko

**Comment by ieugen** [comment]
Thanks, works great. 

And since you've asked.... 

I think I've discovered a bug in CXF, but I'm not sure. Link class messes links up, and doesn't include servlet and JAX-RS application paths.

Description:  
- I have CdiServlet deployed at /rest, 
- I have Jax rs @ApplicationPath /api
- Account resource at /account; 

I expect the following code to return links to my resources:

```
        log.info(" -- <<>> {}", uri.getBaseUri());
        return Response.ok()
                .links(Link.fromResource(AccountResource.class).baseUri(uri.getBaseUri())
                                .rel("account").build(),
                        Link.fromResource(PlatformResource.class).baseUri(uri.getBaseUri())
                                .rel("self").build()).build();
```

However, I get this: 

```
Link=[<http://localhost:9001/>;rel="self", <http://localhost:9001/account>;rel="account"],  
```

And I expected links with full path. UriInfo returns the correct uri. Link messes it up. 

```
INFO  PlatformResource -  -- <<>> http://localhost:9001/rest/api
```

If you can confirm, I'll submit a bug to CXF and perhaps a patch + test.

**Comment by ieugen** [comment]
I've asked on the list. As I was writing it became clear that ti behaves unexpectedly and is most likely a bug. 

Thank you again Andriy,

**Comment by reta** [comment]
Thanks a lot for your findings! Yeah, you are right, the dev list is a better place to troubleshoot this issue, CXF guys are very responsive. 

Thank you!
